version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    environment:
      - DB_HOST=mysql # MySQL service name
      - DB_USER=srikanth
      - DB_PASSWORD=Srikanth@2004
      - DB_NAME=employeeforms
    ports:
      - "5000:5000" # Expose backend port
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Srikanth@2004
      MYSQL_DATABASE: employeeforms
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
